### PR TITLE
2088 fix reporting to rp in travis

### PR DESCRIPTION
**Pull request by AkioFaris**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[46] - Kt1hglhM

**Comment by AkioFaris** [comment]
[46] - Allure report on Netlify: https://5ee108dd3a13d76100240672--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[47] - Ws6G3epO

**Comment by AkioFaris** [comment]
[47] - Allure report on Netlify: https://5ee113a2bf198b5f2b8d1a4d--thirsty-yalow-da011e.netlify.app

**Review by gbuh — APPROVED** [review]

**Pull request merged**
