### PR TITLE
Add genrocket integration

### PR DESCRIPTION
**Pull request by valentynkvasov**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[59] - XZtafwMrhCln

**Comment by AkioFaris** [comment]
[59] - Allure report on Netlify: https://5f11aeea312011095e5ba179--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[62] - Vhr2qYHsfh14

**Comment by AkioFaris** [comment]
[62] - Allure report on Netlify: https://5f11bcc3e2d0e0250a50d3b2--thirsty-yalow-da011e.netlify.app

**Review by ViktarR — APPROVED** [review]

**Comment by AkioFaris** [comment]
[63] - waSwwNE9bPEG

**Comment by AkioFaris** [comment]
[63] - Allure report on Netlify: https://5f154c9b05ec8413817822b1--thirsty-yalow-da011e.netlify.app

**Pull request merged**
