### PR TITLE
2085 add logs and screenshots

### PR DESCRIPTION
**Pull request by AkioFaris**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[44] - Soojq8ma

**Comment by AkioFaris** [comment]
[44] - Allure report on Netlify: https://5ee0af58c8242d3d3e1601dc--thirsty-yalow-da011e.netlify.app

**Review by gbuh — COMMENTED** [review]
Is it really necessary to comment (hide) io.github.epam.testng.TestNGListener in general.xml.

**Comment by AkioFaris** [comment]
[45] - HREkLfNH

**Comment by AkioFaris** [comment]
[45] - Allure report on Netlify: https://5ee0ba5ec8242d971f16053a--thirsty-yalow-da011e.netlify.app

**Review by gbuh — APPROVED** [review]

**Pull request merged**
