### PR TITLE
2119 Add Sealights dependency

### PR DESCRIPTION
**Pull request by AkioFaris**
Implement https://github.com/jdi-testing/jdi-light/issues/2119

### CODE REVIEW

**Comment by AkioFaris** [comment]
[53] - c8yQKtoy

**Comment by AkioFaris** [comment]
[53] - Allure report on Netlify: https://5ef1c1610a6effe0947a9871--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[54] - Ras1H3SM

**Comment by AkioFaris** [comment]
[54] - Allure report on Netlify: https://5ef21a3adb07f2cd3dae2c18--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[55] - dMUfHHFj

**Comment by AkioFaris** [comment]
[55] - Allure report on Netlify: https://5ef21adff8ed54faad30dfef--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[56] - EqoqP1fQ

**Comment by AkioFaris** [comment]
[56] - Allure report on Netlify: https://5ef220643d9ecc3cc5b37ea5--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[57] - 01luRsKm

**Comment by AkioFaris** [comment]
[57] - Allure report on Netlify: https://5ef4d7954f8769f78d643593--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[58] - xWk7rmFr

**Comment by AkioFaris** [comment]
[58] - Allure report on Netlify: https://5ef5b6b2eab879fc95e0b152--thirsty-yalow-da011e.netlify.app

**Review by gbuh — APPROVED** [review]

**Pull request merged**
