### PR TITLE
Disguise the login and password.

### PR DESCRIPTION
**Pull request by gbuh**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[69] - e5AGVvj6iSCa

**Comment by AkioFaris** [comment]
[69] - Allure report on Netlify: https://5f16bdc739b1063819522e29--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[69] - SGoFgGejIQkn

**Comment by AkioFaris** [comment]
[69] - Allure report on Netlify: https://5f16c3d939b10660c2523230--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[70] - HHlF6jB02PI2

**Comment by AkioFaris** [comment]
[70] - Allure report on Netlify: https://5f16d5b8abb36b06d9e2e89f--thirsty-yalow-da011e.netlify.app

**Review by ViktarR — APPROVED** [review]

**Pull request merged**
