### PR TITLE
[FIX] Minio config

### PR DESCRIPTION
**Pull request by valentynkvasov**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[64] - vEdEqQdBbOCp

**Comment by AkioFaris** [comment]
[64] - Allure report on Netlify: https://5f15a7738a3110c4a94d4de3--thirsty-yalow-da011e.netlify.app

**Review by ViktarR — APPROVED** [review]

**Comment by AkioFaris** [comment]
[65] - RWbWdK1yNbhN

**Comment by AkioFaris** [comment]
[65] - Allure report on Netlify: https://5f15cce55c43d44d81cded79--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[66] - m5Dun5kEE5Z6

**Comment by AkioFaris** [comment]
[66] - Allure report on Netlify: https://5f15cf2943f67472493083a5--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[67] - r9YIWUaNmGGo

**Comment by AkioFaris** [comment]
[67] - Allure report on Netlify: https://5f15d838280b6cecdb9573a7--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[68] - DMg9NDNiWB6S

**Comment by AkioFaris** [comment]
[68] - Allure report on Netlify: https://5f15e05672781429a870de96--thirsty-yalow-da011e.netlify.app

**Pull request merged**
