### PR TITLE
Update StaticSite.java

### PR DESCRIPTION
**Pull request by valentynkvasov**

### CODE REVIEW

**Comment by AkioFaris** [comment]
[85] - iwlT2fEc3Y8r

**Comment by AkioFaris** [comment]
[85] - Allure report on Netlify: https://600fe8be0885ddf818d70759--thirsty-yalow-da011e.netlify.app

**Review by HardNorth — APPROVED** [review]

**Comment by AkioFaris** [comment]
[86] - YmUKz17vNA06

**Comment by AkioFaris** [comment]
[86] - Allure report on Netlify: https://600fec9ab9ab33f6502a6b75--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[87] - 37dkjWmlbO2Y

**Comment by AkioFaris** [comment]
[87] - Allure report on Netlify: https://60361ecb04c7f1e5c68a4b90--thirsty-yalow-da011e.netlify.app

**Pull request merged**
