### PR TITLE
Nicer test names

### PR DESCRIPTION
**Pull request by AkioFaris**
Temporary soluntion to get more sentance like test names in Report Portal reports

### CODE REVIEW

**Comment by AkioFaris** [comment]
[50] - 3NYCOG8g

**Comment by AkioFaris** [comment]
[50] - Allure report on Netlify: https://5ee23fc7862acc110d5eaa1f--thirsty-yalow-da011e.netlify.app

**Comment by AkioFaris** [comment]
[51] - 5DZ9coo5

**Comment by AkioFaris** [comment]
[51] - Allure report on Netlify: https://5ee244c1bf561730aa356fae--thirsty-yalow-da011e.netlify.app

**Review by gbuh — APPROVED** [review]

**Comment by AkioFaris** [comment]
[52] - JyW232NW

**Comment by AkioFaris** [comment]
[52] - Allure report on Netlify: https://5ee24837c8f162898f279739--thirsty-yalow-da011e.netlify.app

**Pull request merged**
